name: Auto PR to master

on:
    push:
        branches: ["production"]

permissions:
    contents: write
    pull-requests: write

jobs:
    pull-request:
        name: Open PR to master
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - uses: actions/checkout@v3
              name: checkout

            - uses: repo-sync/pull-request@v2
              name: pull-request
              with:
                  destination_branch: "master"
                  pr_title: "Pulling ${{ github.ref_name }} => master"
                  pr_body: "*An automated PR*:\nfrom ${{ github.ref_name }} => master"
                  github_token: ${{ secrets.GITHUB_TOKEN }}
